### PR TITLE
Fix editor setting initialization for GDExtensions

### LINKED ISSUE #203: EditorSetting limbo_ai/editor/layout not available in Editor
### Godot version

v4.3 stable

### LimboAI version

master branch

### LimboAI variant

GDExtension / AssetLib

### Issue description

Editor reports:
```
editor/editor_settings.cpp:309 - Condition "!props.has(pinfo.name)" is true.
  Couldn't get editor setting: limbo_ai/editor/layout
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
  editor/editor_settings.cpp:309 - Condition "!props.has(pinfo.name)" is true.
  Couldn't get editor setting: limbo_ai/editor/layout
  editor/editor_settings.cpp:309 - Condition "!props.has(pinfo.name)" is true.
  Couldn't get editor setting: limbo_ai/editor/layout
  ```

### How to reproduce

Compile from source, add limboai to addons, run with 4.3 stable.

### PR DESCRIPTION
**Pull request by monxa**
Fixes #203

This commit addresses an issue where editor settings were not properly initialized when using GDExtensions. The problem manifested as an error message: "Condition '!props.has(pinfo.name)' is true" when trying to access the "limbo_ai/editor/layout" setting.

Changes:
- Replace Dictionary with PropertyInfo for adding property information
- Add a safeguard to ensure the setting is explicitly set if not present

### CODE REVIEW

File: editor/limbo_ai_editor_plugin.cpp [hunk 1]
```diff
@@ -1464,12 +1464,17 @@ LimboAIEditor::LimboAIEditor() {
 	EDITOR_SETTINGS()->add_property_hint(PropertyInfo(Variant::INT, "limbo_ai/editor/layout", PROPERTY_HINT_ENUM, "Classic:0,Widescreen Optimized:1"));
```
Comment (limbonaut) [inline editor/limbo_ai_editor_plugin.cpp:1464]: This looks the same as the code below (some of it, anyway). I suggest moving this line outside of conditional compiling, and just leaving inside code that differs.

**Review by limbonaut — CHANGES_REQUESTED** [review]

File: editor/limbo_ai_editor_plugin.cpp (hunk 1 above)
Comment (monxa) [reply editor/limbo_ai_editor_plugin.cpp:1464]: Just checked. godot::EditorSettings.add_property_hint is not available through godot-cpp. At least its not in my generated bindings straight from godot-cpp@master. Is this one of the reasons you did the precompiler differentiation in the first place? How do you want me to proceed?

Comment (limbonaut) [reply editor/limbo_ai_editor_plugin.cpp:1464]: Right, for some reason I read those as the same method :facepalm:

**Comment by limbonaut** [comment]
Thanks for the fix! :+1:
